
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('resources').del()
    .then(function () {
      return Promise.all([
        // Inserts seed entries
        knex('resources').insert({ link: 'https://en.wikipedia.org/wiki/The_Lord_of_the_Rings_(film_series)', item_id: 1}),
        knex('resources').insert({ link: 'http://www.imdb.com/title/tt0120737/', item_id: 1 }),
        knex('resources').insert({ link: 'https://en.wikipedia.org/wiki/Harry_Potter_(film_series)', item_id: 2 }),
        knex('resources').insert({ link: 'http://www.imdb.com/title/tt0241527/', item_id: 2 }),
        knex('resources').insert({ link: 'http://www.hbocanada.com/game-of-thrones', item_id: 3 }),
        knex('resources').insert({ link: 'http://www.imdb.com/title/tt0944947/', item_id: 3 }),
        knex('resources').insert({ link: 'https://www.youtube.com/watch?v=-oX6EokOeqo', item_id: 4 }),
        knex('resources').insert({ link: 'http://www.imdb.com/title/tt3501632/', item_id: 4 }),
        knex('resources').insert({ link: 'https://en.wikipedia.org/wiki/The_Office_(U.S._TV_series)', item_id: 5 }),
        knex('resources').insert({ link: 'http://www.imdb.com/title/tt0386676/', item_id: 5 }),
        knex('resources').insert({ link: 'http://www.imdb.com/title/tt3032476/', item_id: 6 }),
        knex('resources').insert({ link: 'http://www.amc.com/shows/better-call-saul', item_id: 6 }),
        knex('resources').insert({ link: 'https://en.wikipedia.org/wiki/The_Room_(film)', item_id: 7 }),
        knex('resources').insert({ link: 'http://www.imdb.com/title/tt0368226/', item_id: 7 }), 
        knex('resources').insert({ link: 'https://en.wikipedia.org/wiki/The_Lord_of_the_Rings_(film_series)', item_id: 8 }),
        knex('resources').insert({ link: 'http://www.imdb.com/title/tt0120737/', item_id: 8 }),
        knex('resources').insert({ link: 'https://www.goodreads.com/book/show/2429135.The_Girl_with_the_Dragon_Tattoo', item_id: 9 }),
        knex('resources').insert({ link: 'https://en.wikipedia.org/wiki/The_Girl_with_the_Dragon_Tattoo', item_id: 9 }),
        knex('resources').insert({ link: 'https://www.cnn.com/2018/02/09/politics/democratic-memo-trump-wont-declassify/index.html', item_id: 10 }),
        knex('resources').insert({ link: 'https://www.theguardian.com/us-news/2018/feb/10/trump-tweet-domestic-abuse-rob-porter', item_id: 10 }),
        knex('resources').insert({ link: 'https://www.stephenking.com/new_in_stores.html', item_id: 11 }),
        knex('resources').insert({ link: 'http://www.denofgeek.com/us/culture/stephen-king/269987/the-outsider-new-stephen-king-book-release-date-story-details-and-cover', item_id: 11 }),
        knex('resources').insert({ link: 'http://archiecomics.com/characters/new-riverdale/', item_id: 12 }),
        knex('resources').insert({ link: 'https://en.wikipedia.org/wiki/Archie_Comics', item_id: 12 }),
        knex('resources').insert({ link: 'http://vancouversun.com/', item_id: 13 }),
        knex('resources').insert({ link: 'http://vancouversun.com/category/business', item_id: 13 }), 
        knex('resources').insert({ link: 'https://opentextbc.ca/introductiontopsychology/', item_id: 14 }),
        knex('resources').insert({ link: 'http://www.online-psychology-degrees.org/top-10-introductory-psychology-books-for-students/', item_id: 14 }),
        knex('resources').insert({ link: 'https://www.amazon.ca/Best-Joke-Book-Period-Ridiculous/dp/1440583099', item_id: 15 }),
        knex('resources').insert({ link: 'https://www.chapters.indigo.ca/en-ca/home/search/?keywords=joke+book', item_id: 15 }),
        knex('resources').insert({ link: 'https://en.wikipedia.org/wiki/The_Lord_of_the_Rings', item_id: 16 }),
        knex('resources').insert({ link: 'http://www.tolkien.co.uk/category/The+Lord+of+the+Rings', item_id: 16 }),
        knex('resources').insert({ link: 'http://allrecipes.com/recipe/17205/eggs-benedict/', item_id: 17 }),
        knex('resources').insert({ link: 'https://www.yelp.ca/search?find_desc=eggs+benedict&find_loc=Vancouver%2C+BC', item_id: 17 }),
        knex('resources').insert({ link: 'https://www.straight.com/food/833101/12-places-find-brunch-vancouver-will-satisfy-your-morning-cravings', item_id: 18 }),
        knex('resources').insert({ link: 'http://itstodiefor.ca/best-food-in-vancouver/best-brunch-in-vancouver/', item_id: 18 }),
        knex('resources').insert({ link: 'http://www.sushiaoki.ca/', item_id: 19 }),
        knex('resources').insert({ link: 'http://www.sushibarmaumi.ca/', item_id: 19 }), 
        knex('resources').insert({ link: 'http://www.burgerheaven.ca/', item_id: 20 }),
        knex('resources').insert({ link: 'https://www.yelp.ca/c/vancouver/burgers', item_id: 20 }),
        knex('resources').insert({ link: 'https://www.foodnetwork.com/recipes/articles/50-simple-salads', item_id: 21 }),
        knex('resources').insert({ link: 'http://allrecipes.com/recipes/96/salad/', item_id: 21 }),
        knex('resources').insert({ link: 'https://greatist.com/meal-prep', item_id: 22 }),
        knex('resources').insert({ link: 'http://theeverygirl.com/20-lunches-you-can-meal-prep-on-sunday/', item_id: 22 }),
        knex('resources').insert({ link: 'https://www.yelp.ca/search?find_desc=best+lunch&find_loc=Vancouver%2C+BC', item_id: 23 }),
        knex('resources').insert({ link: 'https://www.yelp.ca/search?find_desc=Great+Lunch+Spots&find_loc=Vancouver%2C+BC', item_id: 23 }),
        knex('resources').insert({ link: 'https://www.yelp.ca/biz/whats-up-hot-dog-vancouver', item_id: 24 }),
        knex('resources').insert({ link: 'https://www.yelp.ca/search?cflt=hotdog&find_loc=Vancouver%2C+BC', item_id: 24 }),
        knex('resources').insert({ link: 'https://www.apple.com/ca/shop/iphone/iphone-accessories/cases-protection', item_id: 25 }),
        knex('resources').insert({ link: 'https://www.apple.com/ca/shop/iphone/iphone-accessories/cases-protection', item_id: 25 }),
        knex('resources').insert({ link: 'http://www.seriouseats.com/2017/11/best-immersion-blenders.html', item_id: 26 }),
        knex('resources').insert({ link: 'https://www.bestbuy.ca/en-ca/category/immersion-blenders/37519.aspx', item_id: 26 }),
        knex('resources').insert({ link: 'https://www.amazon.ca/Harry-Potter-Complete-8-Film-Collection/dp/B00UGQ0L20', item_id: 27 }),
        knex('resources').insert({ link: 'https://www.amazon.ca/Harry-Potter-Complete-Collection-Bilingual/dp/B005Q6TB62', item_id: 27 }),
        knex('resources').insert({ link: 'https://www.homedepot.ca/en/home/p.60w-a19-plant-light.1000139130.html', item_id: 28 }),
        knex('resources').insert({ link: 'http://www.hgtv.com/outdoors/flowers-and-plants/houseplants/how-to-choose-the-best-indoor-lighting-for-plants', item_id: 28 }),
        knex('resources').insert({ link: 'https://www.apple.com/ca/shop/product/MD819AM/A/lightning-to-usb-cable-2-m', item_id: 29 }),
        knex('resources').insert({ link: 'https://www.bestbuy.com/site/apple-6-6-lightning-to-usb-2-0-cable-white/2253772.p?skuId=2253772', item_id: 29 })

      ]);
    });
};
